name: screen_recorder
description: Record your Flutter widgets and export the recordings as a GIF
version: 0.2.1
repository: https://github.com/ueman/screenrecorder
issue_tracker: https://github.com/ueman/screenrecorder/issues
funding:
  - https://github.com/sponsors/ueman
  - https://www.buymeacoffee.com/jonasuekoetter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=3.4.0-34.1.pre'

dependencies:
  flutter:
    sdk: flutter
  image: ^4.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
